//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcCV.Models.entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBCVEntities : DbContext
    {
        public DBCVEntities()
            : base("name=DBCVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLADMİN> TBLADMİN { get; set; }
        public virtual DbSet<TBLDENEYİM> TBLDENEYİM { get; set; }
        public virtual DbSet<TBLEGİTİM> TBLEGİTİM { get; set; }
        public virtual DbSet<TBLHAKKIMDA> TBLHAKKIMDA { get; set; }
        public virtual DbSet<TBLİLETİŞİM> TBLİLETİŞİM { get; set; }
        public virtual DbSet<TBLÖDÜLLER> TBLÖDÜLLER { get; set; }
        public virtual DbSet<TBLSERTİFİKA> TBLSERTİFİKA { get; set; }
        public virtual DbSet<TBLYETENEK> TBLYETENEK { get; set; }
        public virtual DbSet<TblSosyalMedya> TblSosyalMedya { get; set; }
    }
}
