//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcCV.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLHAKKIMDA
    {
        public int ID { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string ADRES { get; set; }
        public string TELEFON { get; set; }
        public string MAİL { get; set; }
        public string ACIKLAMA { get; set; }
        public string RESİM { get; set; }
    }
}
